version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: show-branch
          command: 'echo ${CIRCLE_BRANCH}'
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: 'npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: 'npm run build'
      - run:
          name: list
          command: 'ls -l'
      - run:
          name: list
          command: 'ls -l ~/nc'
  deploy:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - run:
          name: list
          command: 'ls -l'
      - run:
          name: list
          command: 'ls -l ~/nc'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: deploy_master_to_firebase
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy